apiVersion: v1
kind: Service
metadata:
  name: phpwebserver-service
  labels:
    app: phpwebserver
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31212
  selector:
    app: phpwebserver
